# Generated by Django 3.2.18 on 2023-12-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20231205_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
