# Generated by Django 3.2.18 on 2023-12-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_auto_20231205_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='cancel',
        ),
        migrations.AddField(
            model_name='airline',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='flight',
            name='cancel_percent',
            field=models.SmallIntegerField(default=0, help_text='Cancellation penalty percentage'),
        ),
        migrations.AddField(
            model_name='flight',
            name='remaining',
            field=models.IntegerField(default=0, help_text='Remaining tickets'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats',
            field=models.IntegerField(help_text='The number of seats'),
        ),
        migrations.CreateModel(
            name='AirPlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.DateField(help_text='Year of construction')),
                ('manufacturer', models.CharField(help_text='Manufacturer', max_length=30)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.airline')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.airplane'),
        ),
    ]
