# Generated by Django 3.2.18 on 2023-12-20 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_auto_20231215_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_of_flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'list of flights',
            },
        ),
        migrations.AlterField(
            model_name='airline',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.airplane'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='remaining',
            field=models.IntegerField(help_text='Remaining tickets'),
        ),
    ]
