# Generated by Django 3.2.18 on 2023-12-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_auto_20231220_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='Logo',
            new_name='logo',
        ),
    ]
