# Generated by Django 3.2.18 on 2023-12-05 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20231205_2236'),
        ('customer', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fly',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
    ]
