# Generated by Django 3.2.18 on 2023-12-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20231205_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fly',
            new_name='flight',
        ),
    ]
