# Generated by Django 3.2.18 on 2023-12-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20231220_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.ticket'),
        ),
    ]
