# Generated by Django 3.2.18 on 2023-12-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('check', 'Check Out'), ('paid', 'Paid'), ('canceld', 'Canceled'), ('not_defind', 'not_defind')], default='not_defind', max_length=10),
        ),
    ]
