# Generated by Django 3.2.18 on 2024-01-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('check', 'Check Out'), ('paid', 'Paid'), ('canceld', 'Canceld')], default='check', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('check', 'Check Out'), ('paid', 'Paid'), ('canceld', 'Canceld')], default='check', max_length=10),
        ),
    ]
