# Generated by Django 3.2.18 on 2024-01-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20240104_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unique_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
